""" Databases mimetypes

http://en.wikipedia.org/wiki/List_of_file_formats#Database
"""
MIMETYPES = (
 {'extensions': ['udl'],
  'icon': 'application.png',
  'mimetype': 'application/x-udl',
  'title': 'Universal Data Link'},
 {'extensions': ['sdb'],
  'icon': 'application.png',
  'mimetype': 'application/x-sdb',
  'title': "StarOffice's StarBase"},
 {'extensions': ['rin'],
  'icon': 'application.png',
  'mimetype': 'application/x-rin',
  'title': 'Sage Retrieve 4GL index file'},
 {'extensions': ['rel'],
  'icon': 'application.png',
  'mimetype': 'application/x-rel',
  'title': 'Sage Retrieve 4GL data file'},
 {'extensions': ['prc'],
  'icon': 'application.png',
  'mimetype': 'application/x-prc',
  'title': 'Palm OS resource database'},
 {'extensions': ['pdx'],
  'icon': 'application.png',
  'mimetype': 'application/x-pdx',
  'title': 'Corel Paradox database management'},
 {'extensions': ['pdi'],
  'icon': 'application.png',
  'mimetype': 'application/x-pdi',
  'title': 'Portable Database Image'},
 {'extensions': ['nv2'],
  'icon': 'application.png',
  'mimetype': 'application/x-nv2',
  'title': 'QW Page NewViews object oriented accounting database'},
 {'extensions': ['ntf'],
  'icon': 'application.png',
  'mimetype': 'application/x-ntf',
  'title': 'Lotus Notes database design template'},
 {'extensions': ['wmdb'],
  'icon': 'application.png',
  'mimetype': 'application/x-ms-wmdb',
  'title': 'Windows Media Database'},
 {'extensions': ['kexic'],
  'icon': 'application.png',
  'mimetype': 'application/x-kexic',
  'title': 'Shortcut to a Kexi database on a server'},
 {'extensions': ['kexi'],
  'icon': 'application.png',
  'mimetype': 'application/x-kexi',
  'title': 'Kexi database'},
 {'extensions': ['gdb'],
  'icon': 'application.png',
  'mimetype': 'application/x-gdb',
  'title': 'Borland InterBase Databases'},
 {'extensions': ['fp', 'fp3', 'fp5', 'fp7'],
  'icon': 'application.png',
  'mimetype': 'application/x-filemaker',
  'title': 'FileMaker Pro'},
 {'extensions': ['fdb'],
  'icon': 'application.png',
  'mimetype': 'application/x-fdb',
  'title': 'Firebird Databases, Navision Database'},
 {'extensions': ['ess'],
  'icon': 'application.png',
  'mimetype': 'application/x-ess',
  'title': 'EGT SmartSense'},
 {'extensions': ['egt'],
  'icon': 'application.png',
  'mimetype': 'application/x-egt',
  'title': 'EGT Universal Document'},
 {'extensions': ['eap'],
  'icon': 'application.png',
  'mimetype': 'application/x-eap',
  'title': 'Enterprise Architect Project'},
 {'extensions': ['db'],
  'icon': 'application.png',
  'mimetype': 'application/x-database',
  'title': 'Paradox, SQLite'},
 {'extensions': ['daf'],
  'icon': 'application.png',
  'mimetype': 'application/x-daf',
  'title': 'Digital Anchor data'},
 {'extensions': ['chml'],
  'icon': 'application.png',
  'mimetype': 'application/x-chml',
  'title': 'Krasbit Technologies Encrypted database'},
 {'extensions': ['box'],
  'icon': 'application.png',
  'mimetype': 'application/x-box',
  'title': 'Lotus Notes Post Office mail routing database'},
 {'extensions': ['adt', 'ads'],
  'icon': 'application.png',
  'mimetype': 'application/x-adt',
  'title': 'Sybase Advantage Database Server'},
 {'extensions': ['wdb'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.ms-works',
  'title': 'Microsoft Works Database'},
 {'extensions': ['adp'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.ms-access',
  'title': 'Microsoft Access project'},
 {'extensions': ['ldb'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.ms-access',
  'title': 'Temporary database'},
 {'extensions': ['mde'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.ms-access',
  'title': 'Compiled Microsoft Database'},
 {'extensions': ['mdf'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.ms-access',
  'title': 'Microsoft SQL Server Database'},
 {'extensions': ['nsf'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.lotus-database',
  'title': 'Lotus Notes database'},
 {'extensions': ['ncf'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.lotus-conf',
  'title': 'Lotus Notes configuration file'},
 {'extensions': ['apr'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.lotus-approach',
  'title': 'Lotus Approach data entry & reports'},
 {'extensions': ['ora'],
  'icon': 'application.png',
  'mimetype': 'application/oracle',
  'title': 'Oracle tablespace'},
 {'extensions': ['myd'],
  'icon': 'application.png',
  'mimetype': 'application/mysql-table',
  'title': 'MySQL MyISAM table data'},
 {'extensions': ['myi'],
  'icon': 'application.png',
  'mimetype': 'application/mysql-index',
  'title': 'MySQL MyISAM table index'},
 {'extensions': ['accdb'],
  'icon': 'application.png',
  'mimetype': 'application/msaccess',
  'title': 'Microsoft Database'},
)
