""" Geographic information system

http://en.wikipedia.org/wiki/List_of_file_formats#Geographic_information_system
"""
MIMETYPES = (
 {'extensions': ['dem'],
  'icon': 'application.png',
  'mimetype': 'application/x-dem',
  'title': 'USGS DEM file format'},
 {'extensions': ['e00'],
  'icon': 'application.png',
  'mimetype': 'application/x-e00',
  'title': 'ARC/INFO interchange file format'},
 {'extensions': ['geotiff'],
  'icon': 'application.png',
  'mimetype': 'image/geotiff',
  'title': 'Geographically located raster data'},
 {'extensions': ['gpx'],
  'icon': 'application.png',
  'mimetype': 'application/x-gpx',
  'title': 'XML-based interchange format'},
 {'extensions': ['mxd'],
  'icon': 'application.png',
  'mimetype': 'application/x-mxd',
  'title': 'ESRI ArcGIS project file'},
 {'extensions': ['shp'],
  'icon': 'application.png',
  'mimetype': 'application/x-qgis',
  'title': 'ESRI shapefile'},
 {'extensions': ['tab'],
  'icon': 'application.png',
  'mimetype': 'application/x-tab',
  'title': 'MapInfo Table file format'},
 {'extensions': ['dted'],
  'icon': 'application.png',
  'mimetype': 'application/x-dted',
  'title': 'Digital Terrain Elevation Data'},
 {'extensions': ['kml'],
  'icon': 'application.png',
  'mimetype': 'application/vnd.google-earth.kml+xml',
  'title': 'Keyhole Markup Language'},
)
