# -*- coding: utf-8 -*-

__author__ = """European Environment Agency (EEA)"""
__docformat__ = 'plaintext'

from parser import MigrationObject

def getOrganisationsData():
    """ Returns organisations data
    """
    res = {}
    providers = [ORGANISATIONS_DS_DATA, ORGANISATIONS_MG_DATA]

    for prov in providers:
        for key in prov.keys():
            data = prov[key]
            res[key] = MigrationObject()
            for prop in data.keys():
                res[key].set(prop, data[prop])
    return res

ORGANISATIONS_DS_DATA = {
'EEA': {
    'UID': 'EEA',
    'title': 'European Environment Agency',
    'description': 'Data sets used in its periodical reports. The data sets contain aggregated data, typically on a country level, with geographical coverage of at least the 15 EU Member States.',
    'organisationUrl': 'http://www.eea.europa.eu',
    'location': 'Kongens Nytorv 6, 1050, Copenhagen, Denmark',
    'address': 'Kongens Nytorv 6, 1050, Copenhagen, Denmark',
    'data_policy': ''
},
'ETC-ACC': {
    'UID': 'ETC-ACC',
    'title': 'The European Topic Centre on Air and Climate Change',
    'description': 'The ETC/ACC supports the EEA in all its tasks relating to air and climate change issues.',
    'organisationUrl': 'http://air-climate.eionet.europa.eu',
    'location': '',
    'data_policy': ''
},
'ETC-LUSI': {
    'UID': 'ETC-LUSI',
    'title': 'The European Topic Centre on Land Use and Spatial Information',
    'description': 'The ETC/LUSI supports the EEA in its work of collecting, analysing, evaluating and synthesising information relevant to national and international policies for the environment and for sustainable development.',
    'organisationUrl': 'http://terrestrial.eionet.europa.eu',
    'location': '',
    'data_policy': ''
},
'ETC-NPB': {
    'UID': 'ETC-NPB',
    'title': 'The European Topic Centre on Nature Protection and Biodiversity',
    'description': 'The ETC/NPB supports the EEA in its work of collecting, analysing, evaluating and synthesising information relevant to national and international policies for the environment and for sustainable development.',
    'organisationUrl': 'http://biodiversity.eionet.europa.eu',
    'location': '',
    'data_policy': ''
},
'ETC-WTR': {
    'UID': 'ETC-WTR',
    'title': 'The European Topic Centre on Water',
    'description': 'The ETC/WTR is an international consortium brought together to support the EEA in its mission to deliver timely, targeted, relevant and reliable information to policy-makers and the public for the development and implementation of sound environmental policies in the European Union and other EEA member countries.',
    'organisationUrl': 'http://water.eionet.europa.eu',
    'location': '',
    'data_policy': ''
},
'FMA': {
    'UID': 'FMA',
    'title': 'Applied Meteorology Foundation (FMA)',
    'description': 'Applied Meteorology Foundation (FMA)',
    'organisationUrl': 'http://www.ibimet.cnr.it/programmi/Pcase/index.htm',
    'location': '',
    'data_policy': ''
},
'BL': {
    'UID': 'BLF',
    'title': 'BirdLife',
    'description': "BirdLife International is a global alliance of conservation organisations working together for the world's birds and people",
    'organisationUrl': 'http://www.birdlife.net',
    'location': '',
    'data_policy': ''
},
'CE': {
    'UID': 'CE',
    'title': 'Council of Europe',
    'description': "The Council of Europe launched its environment programme in 1961, to deal with one of the issues now perceived as one of the main challenges that Europe will have to face in the 21st century. The Council of Europe's activities in this field focus on the conservation of nature and landscapes.",
    'organisationUrl': 'http://www.coe.int',
    'location': '',
    'data_policy': ''
},
'DEFA': {
    'UID': 'DEFA',
    'title': 'Directorate-general for Economic and Financial Affairs',
    'description': 'This is where you find information about economic and financial issues in the European Union',
    'organisationUrl': 'http://ec.europa.eu/economy_finance/index_en.htm',
    'location': '',
    'data_policy': ''
},
'DIS-MED': {
    'UID': 'DIS-MED',
    'title': 'Desertification Information System for the Mediterranean',
    'description': 'The objective of the DIS/MED project is to improve the capacity of national administrations in the Mediterranean countries to effectively programme measures and policies to combat desertification and the effects of drought.',
    'organisationUrl': 'http://dismed.eionet.europa.eu',
    'location': '',
    'data_policy': ''
},
'WCU': {
    'UID': 'WCU',
    'title': 'The World Conservation Union',
    'description': 'The World Conservation Union is the world’s largest and most important conservation network. The Union brings together 82 States, 111 government agencies, more than 800 non-governmental organizations (NGOs), and some 10,000 scientists and experts from 181 countries in a unique worldwide partnership.',
    'organisationUrl': 'http://www.iucn.org',
    'location': '',
    'data_policy': ''
},
'DGE': {
    'UID': 'DGE',
    'title': 'Directorate-general for Environment',
    'description': 'Environmental statistics compiled by the DG Environment ',
    'organisationUrl': 'http://ec.europa.eu/dgs/environment/index_en.htm',
    'location': '',
    'data_policy': ''
},
'EBCC': {
    'UID': 'EBCC',
    'title': 'European Bird Census Council',
    'description': 'EBCC',
    'organisationUrl': 'http://www.ebcc.info',
    'location': '',
    'data_policy': ''
},
'IGCRM': {
    'UID': 'IGCRM',
    'title': 'Institute of Geodesy, Cartography and Remote Sensing',
    'description': 'The Institute of Geodesy, Cartography and Remote Sensing (FÖMI) has been founded in 1967. The Institute is the central surveying and mapping organisation of all official activities in Hungary in the field of land management, surveying and mapping. It is financed by the state budget and has the competence of a national authority. Its direct professional supervisory authority is the Ministry of Agriculture and Rural Development, Department of Land Administration and Geoinformation.',
    'organisationUrl': 'http://www.fomi.hu/honlap/angol/Default.htm',
    'location': '',
    'data_policy': ''
},
'NGDC': {
    'UID': 'NGDC',
    'title': "NOAA's National Geophysical Data Center (NGDC)",
    'description': "NOAA's National Geophysical Data Center (NGDC) provides scientific stewardship, products, and services for geophysical data describing the sea floor, solid earth, and solar-terrestrial environment, including Earth observations from space. ",
    'organisationUrl': 'http://www.ngdc.noaa.gov',
    'location': '',
    'data_policy': ''
},
'ICES': {
    'UID': 'ICES',
    'title': 'International Council for the Exploration of the Sea',
    'description': 'Marine ecosystem statistics compiled by the ICES',
    'organisationUrl': 'http://www.ices.dk',
    'location': 'Palægade 2-4, DK - 1261, Copenhagen, Denmark',
    'address': 'Palægade 2-4, DK - 1261, Copenhagen, Denmark',
    'data_policy': ''
},
'RSPB': {
    'UID': 'RSPB',
    'title': 'Royal Society for the Protection of Birds',
    'description': 'The RSPB is the UK charity working to secure a healthy environment for birds and wildlife, helping to create a better world for us all.',
    'organisationUrl': 'http://www.rspb.org.uk',
    'location': '',
    'data_policy': ''
},
'SOEC': {
    'UID': 'SOEC',
    'title': 'Statistical Office of the European Communities',
    'description': 'The key role of Eurostat is to supply statistical data to the Commission and other European Institutions so they can define, implement and analyse Community policies. ',
    'organisationUrl': 'http://epp.eurostat.ec.europa.eu',
    'location': 'Bâtiment Jean Monnet Rue Alcide de Gasperi, L-2920, Luxembourg, Luxembourg',
    'address': 'Bâtiment Jean Monnet Rue Alcide de Gasperi, L-2920, Luxembourg, Luxembourg',
    'data_policy': ''
},
'STAN': {
    'UID': 'STAN',
    'title': 'Statistics Netherlands',
    'description': 'Statistics Netherlands is responsible for collecting, processing and publishing statistics to be used in practice, by policymakers and for scientific research. In addition to its responsibility for (official) national statistics, Statistics Netherlands also has the task of producing European (community) statistics. The legal basis for Statistics Netherlands and its work is the Act of 20 November 2003 governing the central bureau of statistics (Statistics Netherlands).',
    'organisationUrl': 'http://www.cbs.nl/en-GB/default.htm',
    'location': '',
    'data_policy': ''
},
'FAO': {
    'UID': 'FAO',
    'title': 'The Food and Agriculture Organisation',
    'description': 'The Food and Agriculture Organization of the United Nations leads international efforts to defeat hunger. Serving both developed and developing countries, FAO acts as a neutral forum where all nations meet as equals to negotiate agreements and debate policy. FAO is also a source of knowledge and information.',
    'organisationUrl': 'http://www.fao.org/',
    'location': 'Viale delle Terme di Caracalla, 00100, Rome, Italy',
    'address': 'Viale delle Terme di Caracalla, 00100, Rome, Italy',
    'data_policy': ''
},
'JRC': {
    'UID': 'JRC',
    'title': 'The Joint Research Centre',
    'description': 'The Joint Research Centre is the scientific and technical research laboratory of the European Union and part of the European Commission. It is a directorate-general, and provides scientific advice and the technical know-how for supporting EU policies. Its status as a Commission service, which guarantees its independence from private and national interests, is crucial for pursuing its mission.',
    'organisationUrl': 'http://www.jrc.it',
    'location': 'Joint Research Centre, Institute for Environment and Sustainability, TP 262, 21020 Ispra (VA), Italy',
    'address': 'Joint Research Centre, Institute for Environment and Sustainability, TP 262, 21020 Ispra (VA), Italy',
    'data_policy': ''
},
'UNECE': {
    'UID': 'UNECE',
    'title': 'The United Nations Economic Commission for Europe (Environment and Human Settlements Division)',
    'description': 'UNECE Environment and Human Settlements Division.',
    'organisationUrl': 'http://www.unece.org/env',
    'location': '',
    'data_policy': ''
},
'UNEP': {
    'UID': 'UNEP',
    'title': 'The United Nations Environment Programme',
    'description': 'Statistics compiled by the United Nations Environment Programme ',
    'organisationUrl': 'http://www.unep.org',
    'location': '',
    'data_policy': ''
},
'ABER': {
    'UID': 'ABER',
    'title': 'The University of Wales, Aberystwyth',
    'description': 'Founded in 1872, Aberystwyth was the first university to be established in Wales. It aims to fulfil its special responsibility for the educational needs of Wales, and to maintain and develop partnerships with industry and other institutions both within Wales and beyond, and also to promote collaboration in teaching and research between the constituent parts of the University of Wales.',
    'organisationUrl': 'http://www.aber.ac.uk',
    'location': '',
    'data_policy': ''
},
'UNEP-WCMC': {
    'UID': 'UNEP-WCMC',
    'title': 'United Nations Environment Programme World Conservation Monitoring Centre',
    'description': 'The UNEP World Conservation Monitoring Centre provides information for policy and action to conserve the living world.',
    'organisationUrl': 'http://www.unep-wcmc.org',
    'location': '',
    'data_policy': ''
},
'UNFCCC': {
    'UID': 'UNFCCC',
    'title': 'United Nations Framework Convention on Climate Change',
    'description': 'The main functions of the secretariat of the UNFCC are to make practical arrangements for sessions of the Convention bodies, to assist Parties in implementing their commitments, to provide support to on-going negotiations and to coordinate with the secretariats of other relevant international bodies, notably the Global Environment Facility (GEF) and its implementing agencies (UNDP, UNEP and the World Bank), the Intergovernmental Panel on Climate Change (IPCC), and other relevant conventions.',
    'organisationUrl': 'http://www.unfccc.int',
    'location': '',
    'data_policy': ''
}
}

ORGANISATIONS_MG_DATA = {
'UotA': {
    'UID': 'UotA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of the Aegean',
    'organisationUrl': 'http://www3.aegean.gr/aegean/en/intro_en.htm',
},
'UNEaSD': {
    'UID': 'UNEaSD',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'United Nations Economic and Social Development',
    'organisationUrl': 'http://www.un.org/esa',
},
'CSO': {
    'UID': 'CSO',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Czech Statistical Office',
    'organisationUrl': 'http://www.czso.cz/eng/redakce.nsf/i/home',
},
'NSaIDC': {
    'UID': 'NSaIDC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'National Snow and Ice Data Center',
    'organisationUrl': 'http://www.nsidc.org/index.html',
},
'NTUA': {
    'UID': 'NTUA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The National Technical University of Athens',
    'organisationUrl': 'http://www.ntua.gr',
},
'GeoV': {
    'UID': 'GeoV',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'GeoVille',
    'organisationUrl': 'http://www.geoville.com',
},
'UDE': {
    'UID': 'UDE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Duisburg-Essen',
    'organisationUrl': 'http://www.uni-duisburg-essen.de/en/international.php',
},
'FTUM': {
    'UID': 'FTUM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Forst TU-Muenchen',
    'organisationUrl': 'http://www.forst.tu-muenchen.de/htdocs/fakul_en.php',
},
'SASA': {
    'UID': 'SASA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Slovenian Academy of Sciences and Arts',
    'organisationUrl': 'http://www.sazu.si',
},
'CHI': {
    'UID': 'CHI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Czech Hydrometeorological Institute',
    'organisationUrl': 'http://www.chmi.cz/indexe.html',
},
'BioInt': {
    'UID': 'BioInt',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Bioversity International',
    'organisationUrl': 'http://www.bioversityinternational.org',
},
'CGD-CAS': {
    'UID': 'CGD-CAS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': "CGD's Climate Analysis Section",
    'organisationUrl': 'http://www.cgd.ucar.edu/cas',
},
'UITP-IAPT': {
    'UID': 'UITP-IAPT',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UITP - International Association of Public Transport',
    'organisationUrl': 'http://www.uitp.org',
},
'MuRe': {
    'UID': 'MuRe',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Munich Re',
    'organisationUrl': 'http://www.munichre.com',
},
'HMRC': {
    'UID': 'HMRC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'HM Revenue and Customs',
    'organisationUrl': 'http://www.hmrc.gov.uk',
},
'FDG': {
    'UID': 'FDG',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Fisheries Directorate-General',
    'organisationUrl': 'http://ec.europa.eu/dgs/fisheries/missn_en.htm',
},
'WWF-UK': {
    'UID': 'WWF-UK',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'WWF UK',
    'organisationUrl': 'http://www.wwf.org.uk',
},
'FEA': {
    'UID': 'FEA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Federal Environmental Agency',
    'organisationUrl': 'http://www.umweltbundesamt.de/index-e.htm',
},
'CCE-SR2005': {
    'UID': 'CCE-SR2005',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'CCE Status Report 2005',
    'organisationUrl': 'http://www.mnp.nl/cce',
},
'KNMI': {
    'UID': 'KNMI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Royal Netherlands Meteorological Institute (KNMI)',
    'organisationUrl': 'http://www.knmi.nl',
},
'IPCC': {
    'UID': 'IPCC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Intergovernmental Panel on Climate Change (IPCC)',
    'organisationUrl': 'http://www.ipcc.ch',
},
'IMR': {
    'UID': 'IMR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Institute of Marine Research, Norway',
    'organisationUrl': 'http://www.imr.no/english/main',
},
'NETCEN': {
    'UID': 'NETCEN',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'NETCEN',
    'organisationUrl': 'http://www.netcen.co.uk',
},
'GFDL': {
    'UID': 'GFDL',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Geophysical Fluid Dynamics Laboratory',
    'organisationUrl': 'http://www.gfdl.noaa.gov',
},
'WetInt': {
    'UID': 'WetInt',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Wetlands International',
    'organisationUrl': 'http://www.wetlands.org',
},
'RME': {
    'UID': 'RME',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Research for Man and Environment',
    'organisationUrl': 'http://www.rivm.nl',
},
'NIWR': {
    'UID': 'NIWR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Norwegian Institute for Water Research',
    'organisationUrl': 'http://www.niva.no/engelsk/welcome.htm',
},
'OECD': {
    'UID': 'OECD',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Organisation for Economic Co-operation and Development',
    'organisationUrl': 'http://www.oecd.org',
},
'UNEP-GRID': {
    'UID': 'UNEP-GRID',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UNEP GRID Warszawa',
    'organisationUrl': 'http://www.gridw.pl',
},
'UFZ': {
    'UID': 'UFZ',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Hermholtz - Centre for environmental research (UFZ)',
    'organisationUrl': 'http://www.ufz.de/index.php?en=11382',
},
'YRS': {
    'UID': 'YRS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Young Researchers of Serbia',
    'organisationUrl': 'http://www.mis.org.yu/index.php?lang=eng',
},
'BIODEPTH': {
    'UID': 'BIODEPTH',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'BIODEPTH',
    'organisationUrl': 'http://www.cpb.bio.ic.ac.uk/BIODEPTH',
},
'AHFOS': {
    'UID': 'AHFOS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Sir Alister Hardy Foundation for Ocean Science',
    'organisationUrl': 'http://www.sahfos.org',
},
'EMEP': {
    'UID': 'EMEP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'EMEP',
    'organisationUrl': 'http://www.emep.int',
},
'NASA-GSFC': {
    'UID': 'NASA-GSFC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'NASA Goddard Space Flight Center',
    'organisationUrl': 'http://atm.wff.nasa.gov',
},
'CIM': {
    'UID': 'CIM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Conseil Insular de Menorca',
    'organisationUrl': 'http://www.cime.es',
},
'CLS': {
    'UID': 'CLS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Collecte Localisation Satellite (CLS)',
    'organisationUrl': 'http://www.cls.fr/welcome_en.html',
},
'ORKUSTOFNUN': {
    'UID': 'ORKUSTOFNUN',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'ORKUSTOFNUN - National Energy Authority',
    'organisationUrl': 'http://www.os.is/page/english',
},
'StoUni': {
    'UID': 'StoUni',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Stockholm University',
    'organisationUrl': 'http://www.su.se',
},
'GIM': {
    'UID': 'GIM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Geographic Information Management',
    'organisationUrl': 'http://www.gim.be',
},
'GORIAE': {
    'UID': 'GORIAE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Global Observation Research Initiative in Alpine Environments',
    'organisationUrl': 'http://www.gloria.ac.at',
},
'RMS': {
    'UID': 'RMS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Royal Meteorological Society',
    'organisationUrl': 'http://www.rmets.org/index.php',
},
'IIASA': {
    'UID': 'IIASA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The International Institute for Applied Systems Analysis (IIASA)',
    'organisationUrl': 'http://www.iiasa.ac.at',
},
'UNEP-MAP': {
    'UID': 'UNEP-MAP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'United Nations Environment Programme / Mediterranean Action Plan',
    'organisationUrl': 'http://www.unepmap.org',
},
'TWB': {
    'UID': 'TWB',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The World Bank',
    'organisationUrl': 'http://www.worldbank.org',
},
'PBL': {
    'UID': 'PBL',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Netherlands Environmental Assessment Agency (PBL)',
    'organisationUrl': 'http://www.planbureauvoordeleefomgeving.nl/en/about_pbl/index.html',
},
'OSPAR': {
    'UID': 'OSPAR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'OSPAR Commision',
    'organisationUrl': 'http://www.ospar.org',
},
'WDMP': {
    'UID': 'WDMP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Worldmapper',
    'organisationUrl': 'http://www.worldmapper.org/index.html',
},
'CRBPO': {
    'UID': 'CRBPO',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Centre for research in biology and bird population (CRBPO)',
    'organisationUrl': 'http://www.mnhn.fr/mnhn/crbpo',
},
'SEPA': {
    'UID': 'SEPA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Swedish Enviromental Protection Agency',
    'organisationUrl': 'http://internat.environ.se',
},
'TRS': {
    'UID': 'TRS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Royal Society',
    'organisationUrl': 'http://royalsociety.org',
},
'UDE-RG': {
    'UID': 'UDE-RG',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University Duisburg-Essen, Research Group',
    'organisationUrl': 'http://www.uni-due.de/hydrobiology',
},
'CSO': {
    'UID': 'CSO',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Czech Society for Ornithology',
    'organisationUrl': 'http://www.birdlife.cz/index.php?a=cat.53',
},
'CoBa': {
    'UID': 'CoBa',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Collins Bartholomew',
    'organisationUrl': 'http://www.bartholomewmaps.com',
},
'CERFA': {
    'UID': 'CERFA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Center for Ecological Research and Forestry Applications',
    'organisationUrl': 'http://www.creaf.uab.es',
},
'UniBe': {
    'UID': 'UniBe',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Bern',
    'organisationUrl': 'http://www.unibe.ch/eng',
},
'IRICP': {
    'UID': 'IRICP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'International Research Institute for Climate Prediction',
    'organisationUrl': 'http://iri.columbia.ed',
},
'GNOO': {
    'UID': 'GNOO',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'National Group for Operational Oceanography (GNOO)',
    'organisationUrl': 'http://gnoo.bo.ingv.it/index.php?lang=en',
},
'MSU': {
    'UID': 'MSU',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Moscow State University',
    'organisationUrl': 'http://www.msu.ru/en',
},
'AMAP': {
    'UID': 'AMAP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'AMAP International Datacentre for Radioactivity',
    'organisationUrl': 'http://amap.nrpa.no/index.htm',
},
'DGRP': {
    'UID': 'DGRP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Directorate-general for Regional Policy',
    'organisationUrl': 'http://ec.europa.eu/dgs/regional_policy/index_en.htm',
},
'FiMI': {
    'UID': 'FiMI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Finnish Meteorological Institute',
    'organisationUrl': 'http://fmi.fi/en/index.html',
},
'IPG': {
    'UID': 'IPG',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Institute for Planetary Geodesy',
    'organisationUrl': 'http://www.tu-dresden.de/ipg/hometpg.html',
},
'HMEP': {
    'UID': 'HMEP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Hungarian Ministry for Environmental Protection',
    'organisationUrl': 'http://www.ktm.hu',
},
'UNECE': {
    'UID': 'UNECE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The United Nations Economic Commission for Europe (Forest Resources Assessment)',
    'organisationUrl': 'http://www.unece.org/trade/timber/fra/welcome.htm',
},
'NEBNIA': {
    'UID': 'NEBNIA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The North European and Baltic Network on Invasive Alien species (NOBANIS)',
    'organisationUrl': 'http://www.nobanis.org',
},
'ECNC': {
    'UID': 'ECNC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Centre for Nature Conservation',
    'organisationUrl': 'http://www.ecnc.nl/index.html',
},
'ACRI-ST': {
    'UID': 'ACRI-ST',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'ACRI-ST (Earth Observation - Environment)',
    'organisationUrl': 'http://www.acri-st.fr/English/index.html',
},
'UEA-CRU': {
    'UID': 'UEA-CRU',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of East Anglia, Climate Research Unit',
    'organisationUrl': 'http://www.cru.uea.ac.uk',
},
'USA-GOV': {
    'UID': 'USA-GOV',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'USA Government',
    'organisationUrl': 'http://www.usa.gov',
},
'AI-RI': {
    'UID': 'AI-RI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Ambiente Italia S.r.l. - Research Institute',
    'organisationUrl': 'http://www.ambienteitalia.it/eng/index.asp',
},
'MNP': {
    'UID': 'MNP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Netherlands Environmental Assessment Agency (MNP)',
    'organisationUrl': 'http://www.mnp.nl/en/index.html',
},
'ETCRWM': {
    'UID': 'ETCRWM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The European Topic Centre on Resource and Waste Management',
    'organisationUrl': 'http://waste.eionet.europa.eu',
},
'UoB': {
    'UID': 'UoB',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Bayreuth',
    'organisationUrl': 'http://www.uni-bayreuth.de/index.html',
},
'CNR': {
    'UID': 'CNR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'National Research Council (CNR)',
    'organisationUrl': 'http://www.cnr.it/sitocnr/Englishversion/Englishversion.html',
},
'NIPH': {
    'UID': 'NIPH',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'National Institute of Public Health, Czech Republic',
    'organisationUrl': 'http://www.szu.cz/English/english.htm',
},
'IVS': {
    'UID': 'IVS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Institut de Veille Sanitaire',
    'organisationUrl': 'http://www.invs.sante.fr',
},
'ISRIC': {
    'UID': 'ISRIC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'International Soil Reference and Information Centre',
    'organisationUrl': 'http://www.isric.org',
},
'GISS': {
    'UID': 'GISS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Goddard Institute for Space Studies',
    'organisationUrl': 'http://www.giss.nasa.gov',
},
'JPL': {
    'UID': 'JPL',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Jet Propulsion Laboratory',
    'organisationUrl': 'http://www.jpl.nasa.gov',
},
'CBD': {
    'UID': 'CBD',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Convention on Biological Diversity',
    'organisationUrl': 'http://www.cbd.int',
},
'UniAbe': {
    'UID': 'UniAbe',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Aberdeen',
    'organisationUrl': 'http://abdn.ac.uk',
},
'IRIECAP': {
    'UID': 'IRIECAP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Indicator reporting on the integration of environmental concerns into agricultural policy',
    'organisationUrl': 'http://webpubs.eea.europa.eu/content/irena/index.htm',
},
'TUM': {
    'UID': 'TUM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Technical University of Munich',
    'organisationUrl': 'http://www.tu-muenchen.de',
},
'UNEP-GRIDG': {
    'UID': 'UNEP-GRIDG',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UNEP GRID Geneva',
    'organisationUrl': 'http://www.grid.unep.ch',
},
'NINR': {
    'UID': 'NINR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Norwegian Institute for Nature Research',
    'organisationUrl': 'http://www.nina.no',
},
'CEH': {
    'UID': 'CEH',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Centre for Ecology and Hydrology (CEH)',
    'organisationUrl': 'http://www.ceh.ac.uk',
},
'SOCSTY': {
    'UID': 'SOCSTY',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Socialstyrelsen',
    'organisationUrl': 'http://www.socialstyrelsen.se',
},
'OCW': {
    'UID': 'OCW',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Organic Centre Wales',
    'organisationUrl': 'http://www.organic.aber.ac.uk/index.shtml',
},
'SGU': {
    'UID': 'SGU',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'SGU - Geological Survey of Sweden',
    'organisationUrl': 'http://www.sgu.se/sgu/en',
},
'TUD': {
    'UID': 'TUD',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Technische Universitat Dresden',
    'organisationUrl': 'http://www.tu-dresden.de',
},
'SIME': {
    'UID': 'SIME',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Superior Institute of Maritime Economy',
    'organisationUrl': 'http://www.isemar.asso.fr/english/index.htm',
},
'HELCOM': {
    'UID': 'HELCOM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Helsinki Commission (HELCOM)',
    'organisationUrl': 'http://www.helcom.fi',
},
'ECDC': {
    'UID': 'ECDC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Centre of Disease Prevention and Control (ECDC)',
    'organisationUrl': 'http://ecdc.europa.eu/en',
},
'NoStr': {
    'UID': 'NoStr',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Nord Stream',
    'organisationUrl': 'http://www.nord-stream.com',
},
'APL': {
    'UID': 'APL',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Applied Physics Laboratory',
    'organisationUrl': 'http://www.apl.washington.ed',
},
'EUNAWSWWS': {
    'UID': 'EUNAWSWWS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Union of National Associations of Water Suppliers and Waste Water Services',
    'organisationUrl': 'http://www.eureau.org',
},
'DGET': {
    'UID': 'DGET',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Directorate-general for Energy and Transport',
    'organisationUrl': 'http://ec.europa.eu/dgs/energy_transport/index_en.html',
},
'CiLo': {
    'UID': 'CiLo',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Parc des cigognes et les loutres',
    'organisationUrl': 'http://www.cigogne-loutre.com',
},
'WGMS': {
    'UID': 'WGMS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'World Glacier Monitoring Service',
    'organisationUrl': 'http://www.geo.unizh.ch/wgms',
},
'UniZu': {
    'UID': 'UniZu',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Zurich',
    'organisationUrl': 'http://www.geo.uzh.ch',
},
'DBC': {
    'UID': 'DBC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Dutch Butterfly Conservation',
    'organisationUrl': 'http://www.vlinderstichting.nl',
},
'MSCE': {
    'UID': 'MSCE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Meteorological Synthesizing Centre-East',
    'organisationUrl': 'http://www.msceast.org',
},
'UNEP-ROE': {
    'UID': 'UNEP-ROE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UNEP - Regional Office for Europe',
    'organisationUrl': 'http://www.unep.ch/roe',
},
'UNECE': {
    'UID': 'UNECE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The United Nations Economic Commission for Europe (Transport division)',
    'organisationUrl': 'http://www.unece.org/trans/Welcome.html',
},
'IEEP': {
    'UID': 'xxxxxx',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Institute for European Policy',
    'organisationUrl': 'http://www.ieep.eu',
},
'BUED': {
    'UID': 'BUED',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Boston University',
    'organisationUrl': 'http://www.bu.ed',
},
'GWR': {
    'UID': 'GWR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Green World Research',
    'organisationUrl': 'http://www.alterra.wur.nl/UK/Home.htm',
},
'CIMG': {
    'UID': 'CIMG',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Central Institute for Meteorology and Geodynamics',
    'organisationUrl': 'http://www.zamg.ac.at',
},
'NERI': {
    'UID': 'NERI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'National Environmental Research Institute',
    'organisationUrl': 'http://www.dmu.dk/International',
},
'BEA': {
    'UID': 'BEA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Barcelona Energy Agency',
    'organisationUrl': 'http://www.barcelonaenergia.cat/homeeng.htm',
},
'ISPRA': {
    'UID': 'ISPRA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'ISPRA',
    'organisationUrl': 'http://www.isprambiente.it/site/en-GB/default.html',
},
'WICEE': {
    'UID': 'WICEE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Wupperthal  institute for climate, Environment and energy',
    'organisationUrl': 'http://www.wupperinst.org/en/home/index.html',
},
'EFI': {
    'UID': 'EFI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Forest Institute',
    'organisationUrl': 'http://www.efi.fi',
},
'LeiUni': {
    'UID': 'LeiUni',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Leiden University',
    'organisationUrl': 'http://www.leidenuniv.nl',
},
'ECMWF': {
    'UID': 'ECMWF',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Centre for Medium-Range Weather Forecasts (ECMWF)',
    'organisationUrl': 'http://www.ecmwf.int',
},
'ICPF': {
    'UID': 'ICPF',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'ICP Forests',
    'organisationUrl': 'http://www.icp-forests.org',
},
'NWRED': {
    'UID': 'NWRED',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Norwegian Water Resources and Energy Directorate',
    'organisationUrl': 'http://www.nve.no',
},
'UNEP-GRID': {
    'UID': 'UNEP-GRID',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UNEP/GRID-Arendal',
    'organisationUrl': 'http://www.grida.no',
},
'UniGro': {
    'UID': 'UniGro',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Groningen',
    'organisationUrl': 'http://www.rug.nl/corporate/index',
},
'JRC-IES': {
    'UID': 'JRC-IES',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'JRC-IES/Land Management and Natural Hazards Unit',
    'organisationUrl': 'http://ies.jrc.ec.europa.eu',
},
'CE-IP': {
    'UID': 'CE-IP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'CarboEurope-IP',
    'organisationUrl': 'http://www.carboeurope.org',
},
'EIHAB': {
    'UID': 'EIHAB',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Initiative on Harmful Algal Blooms',
    'organisationUrl': 'http://www.icm.csic.es/bio/projects/strategy',
},
'DGA': {
    'UID': 'DGA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Directorate-general for Agriculture',
    'organisationUrl': 'http://ec.europa.eu/agriculture/index_en.htm',
},
'IWF': {
    'UID': 'IWF',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Institute for World Forestry',
    'organisationUrl': 'http://www.bfafh.de/indexe.htm',
},
'WWF-CAP': {
    'UID': 'WWF-CAP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'WWF Central Asia Programme',
    'organisationUrl': 'http://www.wwf.ru/eng',
},
'KasUni': {
    'UID': 'KasUni',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Kassel University',
    'organisationUrl': 'http://www.uni-kassel.de',
},
'IHP': {
    'UID': 'IHP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'International Hydrological Programme',
    'organisationUrl': 'http://webworld.unesco.org/water/ihp',
},
'UK-MO': {
    'UID': 'UK-MO',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UK Met Office',
    'organisationUrl': 'http://www.metoffice.com',
},
'MARD': {
    'UID': 'MARD',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Ministry of Agriculture and Rural Development, Hungary',
    'organisationUrl': 'http://www.fvm.hu',
},
'EMSC': {
    'UID': 'EMSC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European-Mediterranean Seismological Centre',
    'organisationUrl': 'http://www.emsc-csem.org',
},
'DTCWR': {
    'UID': 'DTCWR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Danish Topic Centre on Waste and Resources',
    'organisationUrl': 'http://www.wasteandresources.dk',
},
'WHOROE': {
    'UID': 'WHOROE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'World Health Organization Regional Office for Europe',
    'organisationUrl': 'http://www.euro.who.int',
},
'CIRES': {
    'UID': 'CIRES',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Colorado (CIRES)',
    'organisationUrl': 'http://cires.colorado.ed',
},
'ITOPFL': {
    'UID': 'ITOPFL',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The International Tanker Owners Pollution Federation Limited',
    'organisationUrl': 'http://www.itopf.com',
},
'VCA': {
    'UID': 'VCA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Vehicle Certification Agency',
    'organisationUrl': 'http://www.vcacarfueldata.org.uk',
},
'MPIM': {
    'UID': 'MPIM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Max Planck Institute for Meteorology',
    'organisationUrl': 'http://www.mpimet.mpg.de/en/home.html',
},
'DAFI': {
    'UID': 'DAFI',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Department of Agriculture and Food, Ireland',
    'organisationUrl': 'http://www.agriculture.gov.ie/home.jsp',
},
'ODYSSEE': {
    'UID': 'ODYSSEE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'ODYSSEE - Energy Efficiency Indicators in Europe',
    'organisationUrl': 'http://www.odyssee-indicators.org',
},
'NatCal': {
    'UID': 'NatCal',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': "Nature's Calendar",
    'organisationUrl': 'http://www.naturescalendar.org.uk',
},
'MAHB': {
    'UID': 'MAHB',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The Major Accident Hazards Bureau',
    'organisationUrl': 'http://mahbsrv.jrc.it',
},
'MOHC': {
    'UID': 'MOHC',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Met Office Hadley Centre observations datasets',
    'organisationUrl': 'http://hadobs.metoffice.com',
},
'LMEP': {
    'UID': 'LMEP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Large Marine Ecosystem Program',
    'organisationUrl': 'http://www.edc.uri.edu/lme',
},
'NIAR': {
    'UID': 'NIAR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Norwegian Institute for Air Research',
    'organisationUrl': 'http://www.nilu.no',
},
'DCMR-EPA': {
    'UID': 'DCMR-EPA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'DCMR Environmental Protection Agency',
    'organisationUrl': 'http://www.dcmr.nl/en/index.html',
},
'PoCa': {
    'UID': 'PoCa',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Point Carbon',
    'organisationUrl': 'http://www.pointcarbon.com',
},
'GSE-FM': {
    'UID': 'GSE-FM',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'GSE Forest Monitoring',
    'organisationUrl': 'http://www.gmes-forest.info/index.htm',
},
'PERMOS': {
    'UID': 'PERMOS',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Permafrost Monitoring Switzerland (PERMOS)',
    'organisationUrl': 'http://www.permos.ch',
},
'CraUni': {
    'UID': 'CraUni',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Cranfield University (National Soil Resources Institute)',
    'organisationUrl': 'http://www.landis.org.uk/gateway/ooi/welcome.cfm',
},
'HCMR': {
    'UID': 'HCMR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Hellenic Centre for Marine Research',
    'organisationUrl': 'http://www.hcmr.gr',
},
'GFN': {
    'UID': 'GFN',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'Global Footprint Network',
    'organisationUrl': 'http://www.footprintnetwork.org',
},
'UniAa': {
    'UID': 'UniAa',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Aarhus',
    'organisationUrl': 'http://www.au.dk',
},
'ARCHELON': {
    'UID': 'ARCHELON',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'ARCHELON The Sea Turtle Protection Society of Greece',
    'organisationUrl': 'http://www.archelon.gr',
},
'UNDESA': {
    'UID': 'UNDESA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The United Nations Department of Economic and Social Affairs',
    'organisationUrl': 'http://www.un.org/esa/desa.htm',
},
'IFREMER': {
    'UID': 'IFREMER',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'French institute for marine research (IFREMER)',
    'organisationUrl': 'http://www.ifremer.fr/anglais',
},
'IEA': {
    'UID': 'IEA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'The International Energy Agency',
    'organisationUrl': 'http://www.iea.org',
},
'ICAR': {
    'UID': 'ICAR',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'International Commision for Alpine Rescue',
    'organisationUrl': 'http://www.ikar-cisa.org',
},
'UniNw': {
    'UID': 'UniNw',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'University of Newcastle',
    'organisationUrl': 'http://newcastle.edu.au',
},
'UK-CIP': {
    'UID': 'UK-CIP',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'UK Climate Impacts Programme',
    'organisationUrl': 'http://www.ukcip.org.uk',
},
'INRA': {
    'UID': 'INRA',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'French National Institude for Agricultural Research (INRA)',
    'organisationUrl': 'http://www.international.inra.fr',
},
'EUROCARE': {
    'UID': 'EUROCARE',
    'description': '',
    'location': '',
    'data_policy': '',
    'title': 'European Centre for Agricultural, Regional and Environmental Policy Research - EUROCARE GmbH',
    'organisationUrl': 'http://www.eurocare-bonn.de'
}
}